# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zotify/gui/settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.formLayout = QtWidgets.QFormLayout(self.generalTab)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.generalTab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rootPathEdit = QtWidgets.QLineEdit(self.generalTab)
        self.rootPathEdit.setObjectName("rootPathEdit")
        self.horizontalLayout.addWidget(self.rootPathEdit)
        self.browseBtn = QtWidgets.QPushButton(self.generalTab)
        self.browseBtn.setObjectName("browseBtn")
        self.horizontalLayout.addWidget(self.browseBtn)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.tabWidget.addTab(self.generalTab, "")
        self.downloadsTab = QtWidgets.QWidget()
        self.downloadsTab.setObjectName("downloadsTab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.downloadsTab)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.downloadsTab)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.downloadFormatCombo = QtWidgets.QComboBox(self.downloadsTab)
        self.downloadFormatCombo.setObjectName("downloadFormatCombo")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.downloadFormatCombo)
        self.label_3 = QtWidgets.QLabel(self.downloadsTab)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.downloadQualityCombo = QtWidgets.QComboBox(self.downloadsTab)
        self.downloadQualityCombo.setObjectName("downloadQualityCombo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.downloadQualityCombo)
        self.label_4 = QtWidgets.QLabel(self.downloadsTab)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.realTimeCheckBox = QtWidgets.QCheckBox(self.downloadsTab)
        self.realTimeCheckBox.setText("")
        self.realTimeCheckBox.setObjectName("realTimeCheckBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.realTimeCheckBox)
        self.label_5 = QtWidgets.QLabel(self.downloadsTab)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.skipExistingCheckBox = QtWidgets.QCheckBox(self.downloadsTab)
        self.skipExistingCheckBox.setText("")
        self.skipExistingCheckBox.setObjectName("skipExistingCheckBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.skipExistingCheckBox)
        self.tabWidget.addTab(self.downloadsTab, "")
        self.formattingTab = QtWidgets.QWidget()
        self.formattingTab.setObjectName("formattingTab")
        self.tabWidget.addTab(self.formattingTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.label.setText(_translate("SettingsDialog", "Music Library Path:"))
        self.browseBtn.setText(_translate("SettingsDialog", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), _translate("SettingsDialog", "General"))
        self.label_2.setText(_translate("SettingsDialog", "Download Format:"))
        self.label_3.setText(_translate("SettingsDialog", "Download Quality:"))
        self.label_4.setText(_translate("SettingsDialog", "Download in Real Time:"))
        self.label_5.setText(_translate("SettingsDialog", "Skip Existing Files:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.downloadsTab), _translate("SettingsDialog", "Downloads"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.formattingTab), _translate("SettingsDialog", "Formatting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsDialog = QtWidgets.QDialog()
    ui = Ui_SettingsDialog()
    ui.setupUi(SettingsDialog)
    SettingsDialog.show()
    sys.exit(app.exec_())
